---

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  browser: true

# https://github.com/babel/babel-eslint
parser: babel-eslint

extends:
  - 'airbnb-base'

rules:
  no-console: 0